### ISSUE TITLE
Nonetype object has no is_expr

### ISSUE THREAD

**Issue by stevemk14ebr** [fireeye/FIDL#14]
Python3 latest ida, hash: 3126280e968397a118b2e75e5349ef613e6ea5a1aca458c38a9271490458313c

```
import itertools
from idaapi import *
from idautils import *
from idc import *
import ida_hexrays
import FIDL.decompiler_utils as du

def string_decoder(args):
    if args and args[0].type == 'string':
        s = bytearray.fromhex(args[0].val)
        res = ""
        last = s[0]
        for a,b in zip(s[1:], itertools.cycle('IIDH47ETIBQRYOF258RYOSYW5XVMEYODH257Y')):
            x = a ^ ord(b)
            z = (x - last) % 255
            res+= chr(z)
            last = a
        return res

def get_func_start(xref):
    try:
        if len(get_func_name(xref.frm)) > 0:#get_func_start will crash IDA without this additional check
            if xref.iscode:
                func = get_func(xref.frm)
                find_func_bounds(func, idaapi.FIND_FUNC_DEFINE)
                return func.start_ea
        return 0
    except:
        return 0

def main():
    addr = 0x004808E0
    func_list = []
    if addr is not None:
        for xref in XrefsTo(addr, ida_xref.XREF_ALL):
            f = get_func_start(xref)
            if f == 0:
                print('xref outside of defined function %x' % xref.frm)
            else:
                func_list.append(f)
    func_list = set(func_list)
    count = 0
    for f in func_list:
        c = du.controlFlowinator(ea=f)
        for co in c.calls:
            if co.call_ea == addr:
                t = string_decoder(co.args)
                du.create_comment(co.c,co.ea,'%s' % (t))
                count+=1
    print('calls found %d' % (count))
    
if __name__ == '__main__':
    main()
```

```
Traceback (most recent call last):
  File "<string>", line 53, in <module>
  File "<string>", line 44, in main
  File "C:\Users\steve\AppData\Roaming\Python\Python38\site-packages\FIDL\decompiler_utils.py", line 1402, in __init__
    self._generate_better_cfg()
  File "C:\Users\steve\AppData\Roaming\Python\Python38\site-packages\FIDL\decompiler_utils.py", line 1844, in _generate_better_cfg
    hi = citem2higher(obj)  # cinsn_t
  File "C:\Users\steve\AppData\Roaming\Python\Python38\site-packages\FIDL\decompiler_utils.py", line 530, in citem2higher
    if citem.is_expr():
AttributeError: 'NoneType' object has no attribute 'is_expr'
```

**Comment by stevemk14ebr** [comment]
fixed somewhere after i pulled the latest
